apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-staging
  namespace: staging
spec:
  replicas: 1
  selector:
    matchLabels:
      app: myapp-staging
  template:
    metadata:
      labels:
        app: myapp-staging
    spec:
      containers:
      - name: myapp-staging
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-staging
  namespace: staging
spec:
  selector:
    app: myapp-staging
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
