apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: build-and-deploy-run-1766769614
  namespace: tekton-pipelines
spec:
  pipelineRef:
    name: build-and-deploy
  params:
    - name: APP_REPO
      value: "https://github.com/Galass763/app-repo.git"
    - name: ENV_REPO
      value: "https://github.com/Galass763/env-repo.git"
    - name: IMAGE_NAME
      value: "docker.io/votre-username/myapp"
    - name: IMAGE_TAG
      value: "v1.0.1766769614"
  workspaces:
    - name: shared-workspace
      persistentVolumeClaim:
        claimName: workspace-pvc
  serviceAccountName: tekton-pipeline-sa
