---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone-restricted
  namespace: tekton-pipelines
spec:
  workspaces:
    - name: output
  params:
    - name: url
      type: string
    - name: revision
      type: string
      default: main
  steps:
    - name: clone
      image: bitnami/git:latest
      script: |
        #!/bin/bash
        set -e
        echo "Cloning repository: $(params.url)"
        git clone $(params.url) $(workspaces.output.path)/source
        cd $(workspaces.output.path)/source
        git checkout $(params.revision)
        echo "✅ Clone successful"
        ls -la $(workspaces.output.path)/source
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: git-clone
  namespace: tekton-pipelines
spec:
  description: Clone un repository Git
  params:
    - name: url
      type: string
      description: URL du repository Git
    - name: revision
      type: string
      default: main
      description: Branche ou tag à cloner
  workspaces:
    - name: output
      description: Workspace où cloner le code
  steps:
    - name: clone
      image: bitnami/git:latest
      script: |
        #!/bin/bash
        set -e
        echo "Cloning repository: $(params.url)"
        echo "Revision: $(params.revision)"
        
        git clone $(params.url) /workspace/output/source
        cd /workspace/output/source
        git checkout $(params.revision)
        
        echo "✅ Clone successful"
        ls -la /workspace/output/source
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-image
  namespace: tekton-pipelines
spec:
  description: Build et push image Docker avec Kaniko
  params:
    - name: IMAGE
      type: string
      description: Nom complet de l'image (docker.io/user/app:tag)
    - name: DOCKERFILE
      type: string
      default: Dockerfile
  workspaces:
    - name: source
  steps:
    - name: build-and-push
      image: gcr.io/kaniko-project/executor:v1.9.0
      env:
        - name: DOCKER_CONFIG
          value: /kaniko/.docker
      args:
        - --dockerfile=$(workspaces.source.path)/source/$(params.DOCKERFILE)
        - --context=$(workspaces.source.path)/source
        - --destination=$(params.IMAGE)
        - --cache=true
        - --cache-ttl=24h
        - --skip-tls-verify
        - --insecure
        - --insecure-pull
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-manifest
  namespace: tekton-pipelines
spec:
  description: Mise à jour du manifest Kubernetes avec la nouvelle image
  params:
    - name: IMAGE
      type: string
    - name: GIT_REPO
      type: string
    - name: GIT_EMAIL
      type: string
      default: tekton@example.com
    - name: GIT_NAME
      type: string
      default: Tekton Pipeline
    - name: MANIFEST_PATH
      type: string
      default: manifests/deployment.yaml
  workspaces:
    - name: source
  steps:
    - name: update-yaml
      image: alpine/git:latest
      script: |
        #!/bin/sh
        set -e
        
        echo "📦 Cloning env-repo..."
        git clone $(params.GIT_REPO) /workspace/source/env-repo
        cd /workspace/source/env-repo
        
        echo "⚙️  Configuring git..."
        git config user.email "$(params.GIT_EMAIL)"
        git config user.name "$(params.GIT_NAME)"
        
        echo "🔄 Updating image in $(params.MANIFEST_PATH)..."
        sed -i "s|image:.*nginx.*|image: $(params.IMAGE)|g" $(params.MANIFEST_PATH)
        
        echo "📝 Git diff:"
        git diff
        
        echo "💾 Committing changes..."
        git add .
        git commit -m "Update image to $(params.IMAGE)" || echo "No changes"
        
        echo "⬆️  Pushing to main..."
        git push origin main || echo "Push may need auth"
        
        echo "✅ Done!"
---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: run-tests
  namespace: tekton-pipelines
spec:
  description: Exécuter les tests unitaires
  workspaces:
    - name: source
  steps:
    - name: test
      image: python:3.9-slim
      script: |
        #!/bin/bash
        set -e
        
        cd /workspace/source/source
        
        echo "📦 Installing dependencies..."
        pip install --quiet -r src/requirements.txt
        pip install --quiet pytest pytest-cov
        
        echo "🧪 Running tests..."
        python -m pytest tests/ -v --cov=src
        
        echo "✅ Tests passed!"
---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: build-and-deploy
  namespace: tekton-pipelines
spec:
  description: Pipeline complet de build et déploiement
  
  params:
    - name: APP_REPO
      type: string
    - name: ENV_REPO
      type: string
    - name: IMAGE_NAME
      type: string
    - name: IMAGE_TAG
      type: string
      default: latest
  
  workspaces:
    - name: shared-workspace
  
  tasks:
    - name: fetch-app-repository
      taskRef:
        name: git-clone-restricted
      params:
        - name: url
          value: $(params.APP_REPO)
        - name: revision
          value: main
      workspaces:
        - name: output
          workspace: shared-workspace
    
    - name: run-tests
      taskRef:
        name: run-tests
      runAfter:
        - fetch-app-repository
      workspaces:
        - name: source
          workspace: shared-workspace
    
    - name: build-push-image
      taskRef:
        name: build-image
      runAfter:
        - run-tests
      params:
        - name: IMAGE
          value: "$(params.IMAGE_NAME):$(params.IMAGE_TAG)"
      workspaces:
        - name: source
          workspace: shared-workspace
    
    - name: update-deployment-manifest
      taskRef:
        name: update-manifest
      runAfter:
        - build-push-image
      params:
        - name: IMAGE
          value: "$(params.IMAGE_NAME):$(params.IMAGE_TAG)"
        - name: GIT_REPO
          value: $(params.ENV_REPO)
      workspaces:
        - name: source
          workspace: shared-workspace
