apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp-production
  namespace: production
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp-production
  template:
    metadata:
      labels:
        app: myapp-production
    spec:
      containers:
      - name: myapp-production
        image: nginx:alpine
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-production
  namespace: production
spec:
  selector:
    app: myapp-production
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
